### ISSUE TITLE
questions about --max-coverage

### ISSUE THREAD

**Issue by nihilee** [broadinstitute/VariantBam#1]
thanks for this useful tool，but i meet a problem when i use it to downsample a bam file. it seems remove more reads than i think, when i set --max-coverage to 40000, but only get mean coverage ~1200

**Comment by walaj** [comment]
The max coverage just down-samples areas where the point-coverage is
greater than what max coverage is set to. I don't see an inconsistency with
a mean coverage less the max coverage.

**Comment by nihilee** [comment]
> 

sorry for my unclear expression, my problem is i hava a region in chr7 with very high coverage (~100000x):
![image](https://user-images.githubusercontent.com/48557172/151643928-b66711a0-9e1c-4b53-a566-b74a1a4bfea7.png)
 but after i use max-coverage  40000 to downsample it, variantbam give me result like this:
![image](https://user-images.githubusercontent.com/48557172/151643991-09105479-96f5-4464-8b52-b5086221d181.png)
PS: x-asix is region in chr

**Comment by walaj** [comment]
Ahh got it -- yeah that seems like an issue.

Can you use the updated repos? This one is two years more up-to-date. Let
me know on that repos if still having this issue:
https://github.com/walaj/VariantBam
